// Smoke check: index.js importability, the export contract, and the
// host/client markers that implement per-provider off-peak scheduling.
import { name, apply, deliverOnce } from '../index.js'
import { createOffpeakCore } from '../src/core.mjs'
import { readFileSync } from 'node:fs'
import assert from 'node:assert/strict'

assert.equal(name, 'offpeak-queue')
assert.equal(typeof apply, 'function')
assert.equal(typeof deliverOnce, 'function')
assert.equal(typeof createOffpeakCore, 'function')

const client = readFileSync(new URL('../client.js', import.meta.url), 'utf8')
// Native DSH surfaces: composer-right toggle slot, sidebar footer-action slot, modal root.
assert.match(client, /slots\.inject\('conversation\.input\.right'/)
assert.match(client, /slots\.inject\('sidebar\.footer\.action'/)
assert.match(client, /const inject = \['slots', 'sessions'\]/)
assert.match(client, /require\('react-dom\/client'\)/)
assert.match(client, /createRoot\(host\)/)
assert.match(client, /document\.body\.appendChild\(host\)/)
assert.match(client, /@deepseek-ai\/dsh-client-ui-primitives/)
assert.match(client, /IconSendOutline14/)
assert.match(client, /IconQueueOutline14/)
assert.match(client, /IconCloseOutline16/)
assert.match(client, /Tooltip/)
assert.match(client, /data-oq-queue/)
assert.match(client, /data-oq-rail/)
assert.match(client, /:has\(> \[data-slot="sidebar\.footer\.action"\]/)
assert.match(client, /setPlanMode/)
assert.match(client, /inputActions\.setDraft/)
assert.match(client, /sessionFromService/)
assert.match(client, /sessionFromEditor/)
assert.match(client, /session mismatch blocked/)
assert.match(client, /send intercepted:/)
assert.match(client, /sessionPhase/)
assert.match(client, /sessionProvider/)
assert.match(client, /providerLabel/)
assert.match(client, /providers: snap\.providers/)
assert.match(client, /dsh-offpeak is required/)
// Legacy surfaces are gone: no composer dock strip, no native DOM renderer, no local scheduler.
assert.doesNotMatch(client, /native fallback/)
assert.doesNotMatch(client, /data-oq-surface/)
assert.doesNotMatch(client, /DOM probe/)
assert.doesNotMatch(client, /localPhase/)
assert.doesNotMatch(client, /setPeaks|setWeekendsOffPeak|weekend/i)
assert.doesNotMatch(client, /conversation\.composer\.dock/)
assert.doesNotMatch(client, /slots\.inject\('conversation\.input\.dock'/)
assert.doesNotMatch(client, /slots\.inject\('conversation\.composer',/)
// English-only copy for every string this client renders.
assert.doesNotMatch(client, /[\u4e00-\u9fff]/)

const host = readFileSync(new URL('../index.js', import.meta.url), 'utf8')
assert.match(host, /getService\(ctx, 'sessionController'\)/)
assert.match(host, /apiProxy\.sessions\.prompt/)
assert.match(host, /requestId: 'offpeak-queue-' \+ randomUUID\(\)/)
assert.match(host, /mode: 'queue'/)
assert.match(host, /role: 'user'/)
assert.match(host, /id: randomUUID\(\)/)
assert.match(host, /delivery ' \+ item\.id \+ ' target=' \+ item\.sessionId/)
assert.match(host, /resolveSessionPair/)
assert.match(host, /offpeakPhase/)
assert.match(host, /windowKindFor/)
assert.match(host, /providerSummaries/)
assert.match(host, /phaseForItem/)
assert.match(host, /sessionIdFromUrl/)
assert.match(host, /offpeakAvailable/)
assert.match(host, /dsh-offpeak is required/)
assert.doesNotMatch(host, /setPeaks/)
assert.doesNotMatch(host, /setWeekendsOffPeak/)

console.log('smoke OK: host delivery + dsh-offpeak schedules + composer toggle + sidebar entry + queue modal')
